### ISSUE TITLE
JsonDecodeError

### ISSUE THREAD

**Issue by furkansimsekli** [hacettepeoyt/hu-cafeteria-bot#31]
```python
Traceback (most recent call last):
  File "/nix/store/3rw1f1yarsi3xr2kjprmi8xah4hlfrma-python3.12-python-telegram-bot-21.4/lib/python3.12/site-packages/telegram/ext/_application.py", line 1335, in process_update
    await coroutine
  File "/nix/store/3rw1f1yarsi3xr2kjprmi8xah4hlfrma-python3.12-python-telegram-bot-21.4/lib/python3.12/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xpmdzskwgrwycyvhp527cksv3hjg28iq-hu-cafeteria-bot-2.2.0/lib/hu-cafeteria-bot/hu-cafeteria-bot/bot.py", line 70, in send_today
    menu = Helper.get_menu(DB, today_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xpmdzskwgrwycyvhp527cksv3hjg28iq-hu-cafeteria-bot-2.2.0/lib/hu-cafeteria-bot/hu-cafeteria-bot/utils.py", line 285, in get_menu
    menu = json.load(file)[date]
           ^^^^^^^^^^^^^^^
  File "/nix/store/wviq85xs5awfp75mj5sjq9mn1nkqhq12-python3-3.12.4/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/nix/store/wviq85xs5awfp75mj5sjq9mn1nkqhq12-python3-3.12.4/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wviq85xs5awfp75mj5sjq9mn1nkqhq12-python3-3.12.4/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 97078 (char 97077)
```

**Comment by furkansimsekli** [comment]
```
with open(database_path, "r+") as file:
        database_dict = json.load(file)
        database_dict.update(menu_list)
        file.seek(0)
        json.dump(database_dict, file, ensure_ascii=False)
```

Since I don't the truncate the file first, when the new dictionary to be dumped is shorter than the one currently in database (in string representation) there might be leftovers from the old version at the end of line. We assume that the database grow each day when a new menu inserted, but when they change a meal name or something like that, there is a possibility to screw up.
